[package]
name = "_rust_atomicfile"
version = "0.0.0"
edition = "2021"
rust-version = "1.84"

[lib]
name = "_rust_atomicfile"
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"

[dependencies]
dunce = "1.0.5"
pyo3 = { version = "0.23.4", features = [
    "extension-module",
    "generate-import-lib",
] }
tempfile = "3.16.0"
